spring.application.name=movieBuzz

#jdbc properties
spring.datasource.url=jdbc:mysql://localhost:3306/movie_ticket_booking_directory
spring.datasource.username=springstudent
spring.datasource.password=springstudent

spring.security.user.name=saurav
spring.security.user.password=test123

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG

#secret key for jwt
jwt.secret = @Adfdfiiuusaasafdufhdufhduhyduydusduhushsugu29
